Admin_interface/cart/urls.py
from django.urls import path
from cart import views

app_name='cart'

urlpatterns=[
    path('show/',views.show,name='show'),
    path('add/<int:id>/',views.add,name='add'),
    path('remove/<int:id>/',views.remove,name='remove'),
]

Admin_interface/catalogue/urls.py
from django.urls import path
from .views import ProductDetailView

app_name='catalogue'

urlpatterns=[
    path('<slug:slug>',ProductDetailView.as_view(),name='product_detail'),
]

Admin_interface/orders/urls.py
from django.urls import path
from orders import views

app_name = 'orders'

urlpatterns=[
    path('create/',views.checkout,name='checkout')
]

Admin_interface/cart/models.py
from django.db import models

# Create your models here.

Admin_interface/cart/views.py
from django.shortcuts import render,get_object_or_404,redirect
from category.models import Category
from catalogue.models import Product
from .cart import Cart


def add(request,id):
    product=get_object_or_404(Product,id=id)
    cart=Cart(request)
    cart.add(product)
    return redirect('cart:show')

def remove(request,id):
    cart=Cart(request)
    product=get_object_or_404(Product,id=id)
    cart.remove(product)
    return redirect('cart:show')

def show(request):
    cart=Cart(request)
    return render(request,'cart/show_cart.html',{'cart':cart})

Admin_interface/cart/templates/cart/show_cart.html
{% extends 'base.html' %}

{% block content %}
 <div class="jumbotron" style="background: lightsteelblue">
    {% if cart.total_price > 0 %}
        {% for item in cart %}
            {% with product=item.product %}

                <ul class="container" style="background: lightcyan;list-style-type:none;">
                    <li><h2 style="color: lightcoral"><a href="{% url 'catalogue:product_detail' slug=product.slug %}">{{ product.name }}</a></h2></li>
                    <li>Price Per Unit: Rs {{ item.price }}</li>
                    <li>Quantity: {{ item.quantity }}</li>
                        <p></p>
                    <a class="btn btn-info btn-sm" href="{% url 'cart:add' id=product.id %}">ADD</a>
                    <a class="btn btn-warning btn-sm" href="{% url 'cart:remove' id=product.id %}">Remove</a>
                        <p></p>
                </ul>

            {% endwith %}
        {% endfor %}
     <ul class="container" style="list-style-type:none">
         <h5 style="color: black">Total Items: {{ cart|length }}</h5>
         <h5 style="color: black">Pay Rs {{ cart.total_price }}</h5>
         <a class="btn btn-success btn-sm" href="{% url 'orders:checkout' %}">Chekout</a>
     </ul>
 {% else %}
        <div class="container">
            <h3 style="font-family: 'Apple Color Emoji'"> Cart Empty</h3>
            <p></p>
            <a class="btn btn-primary btn-sm" href="{% url 'home' %}">Shop Here</a>
        </div>
 {% endif %}
</div>

{% endblock %}