Admin_interface/cart/urls.py
from django.urls import path
from cart import views

app_name='cart'

urlpatterns=[
    path('show/',views.show,name='show'),
    path('add/<int:id>/',views.add,name='add'),
    path('remove/<int:id>/',views.remove,name='remove'),
]

Admin_interface/catalogue/urls.py
from django.urls import path
from .views import ProductDetailView

app_name='catalogue'

urlpatterns=[
    path('<slug:slug>',ProductDetailView.as_view(),name='product_detail'),
]

Admin_interface/category/urls.py
from django.urls import path
from . import views

app_name = 'category'

urlpatterns=[
    path('', views.ServiceList.as_view(), name='service_list'),
    path('<slug:slug>/',views.ServiceDetailView.as_view(),name='service_detail'),
]

Admin_interface/category/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
class Category(models.Model):
    name=models.CharField(max_length=128,db_index=True,unique=True)
    slug=models.SlugField(db_index=True,unique=True)
    created_on=models.DateTimeField(auto_now_add=True,auto_now=False)
    updated_on=models.DateTimeField(auto_now=True,auto_now_add=False)
    available=models.BooleanField(default=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('cart:category_detail',kwargs={'slug':self.slug})

Admin_interface/category/forms.py
from category.models import Category
from django.forms import ModelForm

Admin_interface/category/views.py
from django.views.generic import DetailView,ListView
from .models import Category

# Create your views here.
class ServiceDetailView(DetailView):
    model = Category
    context_object_name = 'category'
    template_name = 'category/category_detail.html'


class ServiceList(ListView):
    model = Category
    context_object_name = 'services'
    template_name = 'category/service_list.html'

Admin_interface/category/templates/category/category_detail.html
{%  extends 'base.html' %}

{% block content %}
{%  for item in category.products.all %}
    <div class="container" style="border: 5px crimson solid; margin-bottom: 10px; margin-top: 10px">
    <ul><a  href="{% url 'catalogue:product_detail' slug=item.slug %}"><h4>{{ item.name }}</h4></a></ul>
    <ul>{{ item.price }}</ul>
    <p></p>
    </div>
{% endfor %}
{% endblock %}

Admin_interface/category/templates/category/service_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Services</title>
</head>
<body>
<h1>Services Provided</h1>
{% for service in services %}
    <a href="{% url 'category:service_detail' slug=service.slug %}">{{ service.name }}</a>
    <hr>
{% endfor %}
</body>
</html>